@baseAdress = http://localhost:5280
@CategoryId = 08dd01a9-2a70-e38c-4e49-6ce70ac70000
GET {{baseAdress}}/api/categories
Accept: application/json

###
post {{baseAdress}}/api/categories
Accept: application/json
Content-Type:application/json
{
  "name":"Category 1"
}
###

Get {{baseAdress}}/api/categories/{{CategoryId}}
Accept: application/json
###

Delete {{baseAdress}}/api/categories/08dd08ef-e3ac-9a3b-4e49-6ce70ac70000
Accept: application/json
###
post {{baseAdress}}/api/courses
Accept: application/json
Content-Type:application/json
{
  "name": "string",
  "description": "string",
  "price": 0,
  "imageUrl": "string",
  "categoryId": {{@CategoryId}}
}