@baseAdress = http://localhost:5280
@CategoryId = 08dd01b9-9ac9-b213-4e49-6ce70ac70000
GET {{baseAdress}}/api/v1/categories
Accept: application/json

###
post {{baseAdress}}/api/v1/categories
Accept: application/json
Content-Type:application/json
{
  "name":"Category 1"
}
###

Get {{baseAdress}}/api/v1/categories/{{CategoryId}}
Accept: application/json
###

Delete {{baseAdress}}/api/v1/categories/08dd08ef-e3ac-9a3b-4e49-6ce70ac70000
Accept: application/json
###
post {{baseAdress}}/api/v1/courses
Accept: application/json
Content-Type:application/json
{
  "name": "string",
  "description": "string",
  "price": 2,
  "imageUrl": "string",
  "categoryId": "{{CategoryId}}"
}
###

Delete {{baseAdress}}/api/v1/courses/08dd08ef-e3ac-9a3b-4e49-6ce70ac70000
Accept: application/json