@baseAdress = http://localhost:5280

GET {{baseAdress}}/api/categories
Accept: application/json

###
post {{baseAdress}}/api/categories
Accept: application/json
Content-Type:application/json
{
  "name":"Category 1"
}

###
